name: Build and Release .exe

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install PyInstaller and create the .exe
      - name: Build executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile --icon=misc\tool_icon.ico --uac-admin main.py  # Replace with your main script

      # Archive the .exe file for GitHub release
      - name: Archive the .exe
        run: |
          mkdir release
          copy dist\main.exe release\main.exe
          echo "Creating archive complete"

      # Upload to GitHub Releases
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}